"""empty message

Revision ID: 43a65a6592b8
Revises: d5f6d2dfe167
Create Date: 2024-11-05 18:04:56.738929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43a65a6592b8'
down_revision: Union[str, None] = 'd5f6d2dfe167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_chat_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'chat', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_chat_id_fkey', 'message', 'chat', ['chat_id'], ['id'])
    # ### end Alembic commands ###
