"""empty message

Revision ID: d5f6d2dfe167
Revises: 50a2c96aa85a
Create Date: 2024-11-05 02:30:16.042035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f6d2dfe167'
down_revision: Union[str, None] = '50a2c96aa85a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_member_member_id_fkey', 'chat_member', type_='foreignkey')
    op.drop_constraint('chat_member_chat_id_fkey', 'chat_member', type_='foreignkey')
    op.create_foreign_key(None, 'chat_member', 'user', ['member_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_member', 'chat', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_member', type_='foreignkey')
    op.drop_constraint(None, 'chat_member', type_='foreignkey')
    op.create_foreign_key('chat_member_chat_id_fkey', 'chat_member', 'chat', ['chat_id'], ['id'])
    op.create_foreign_key('chat_member_member_id_fkey', 'chat_member', 'user', ['member_id'], ['id'])
    # ### end Alembic commands ###
